name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: [ARM32]

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image for ARMv7 Architecture
      run: docker build . --file Dockerfile 
