# documentation generation for robotic_skin
name: Documentation Generation Github Pages

# only deploys documentation on pushes to master
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install and Build
      run: |
        
        pip install sphinx sphinx-autobuild sphinx_rtd_theme
        sphinx-apidoc -f -o docs robotic_skin
        cd docs
        make clean
        make html
        git status
        
    # deploy to gh pages
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: docs/_build/html # The folder the action should deploy.
