name: Pylint
on: [push]
jobs:
  Pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: pip install -r requirements.txt
      - run: flake8 --ignore=E121,E123,E126,E226,E24,E704,W503,W504,E501 --exclude setup.py
