name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --max-complexity=10 --max-line-length=140 --statistics --exclude setup.py
    - name: Test code
      run: |
        sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
        sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
        
        sudo apt-get update
        sudo apt install ros-melodic-ros-base
        sudo rosdep init
        rosdep update
        echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc
        source ~/.bashrc
        sudo apt install python-rosinstall python-rosinstall-generator python-wstool build-essential
        sudo apt install python3-rosdistro python3-catkin-pkg python3-rospkg python3-rosinstall python3-rosinstall-generator python3-wstool build-essential

        python setup.py test
